### ISSUE TITLE
Add puppeteer MCP server

### ISSUE THREAD

**Issue by blevinstein** [blevinstein/github-agent#13]
Integrate puppeteer to allow the agent to use a browser. See documentation at https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer

For now let's just add the new MCP server to the `lookup` task in agent.yaml, as an experiment. So the lookup task will be able to do wikipedia OR browser-based lookups. We will also need to update that particular step in the workflow to install additional capabilities. Try adding steps like this:

```
      - name: Install chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 136

      - name: Install browsers with Puppeteer
        run: |
          echo "CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
          npx @puppeteer/browsers install chrome-headless-shell@136
          npx @puppeteer/browsers install firefox
```
